version: '3.8'

services:
  catalog-server:
    image: catalog-service
    build:
      context: .
      dockerfile: Dockerfile
      target: catalog
    volumes:
      - ./catalog:/app/catalog:ro
      - ./nginx:/app/nginx:ro
      - ./catalog/database.db:/app/database.db:rw
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1  # Default primary instance
      update_config:
        delay: 10s
      endpoint_mode: dnsrr
    ports:
      - "3001:3001"

  catalog-replica:
    image: catalog-service
    build:
      context: .
      dockerfile: Dockerfile
      target: catalog
    volumes:
      - ./catalog:/app/catalog:ro
      - ./nginx:/app/nginx:ro
      - ./catalog/database-replica.db:/app/database.db:rw  # Separate database for replica
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1  # Single replica instance
      update_config:
        delay: 10s
      endpoint_mode: dnsrr
    ports:
      - "3003:3001"  # Expose replica on different port

  order-server:
    image: order-service
    build:
      context: .
      dockerfile: Dockerfile
      target: order
    volumes:
      - ./order:/app/order:ro
      - ./nginx:/app/nginx:ro
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1  # Default primary instance
      update_config:
        delay: 10s
      endpoint_mode: dnsrr
    depends_on:
      - catalog-server
    ports:
      - "3002:3002"

  order-replica:
    image: order-service
    build:
      context: .
      dockerfile: Dockerfile
      target: order
    volumes:
      - ./order:/app/order:ro
      - ./nginx:/app/nginx:ro
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1  # Single replica instance
      update_config:
        delay: 10s
      endpoint_mode: dnsrr
    ports:
      - "3004:3002"  # Expose replica on different port

  client:
    image: client-service
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    volumes:
      - ./frontend:/app/frontend:ro
    deploy:
      replicas: 1
      update_config:
        delay: 10s
      endpoint_mode: dnsrr
    depends_on:
      - catalog-server
      - order-server
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalog-server
      - catalog-replica
      - order-server
      - order-replica
      - client