version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  catalog-server:
    image: catalog-service
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - app-network

  catalog-server-replica:
    image: catalog-service
    build:
      context: .
    ports:
      - "3009:3001"
    networks:
      - app-network

  order-server:
    image: order-service
    build:
      context: .
    ports:
      - "3002:3002"
    networks:
      - app-network

  order-server-replica:
    image: order-service
    build:
      context: .
    ports:
      - "3008:3002"
    networks:
      - app-network

  frontend:
    image: frontend-service
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
