version: '3.8'

services:
  catalog-server:
    image: catalog-service
    build:
      context: .  
      dockerfile: Dockerfile
      target: catalog  
    volumes:
      - ./catalog:/app/catalog:ro  
      - ./nginx:/app/nginx:ro 
      - ./catalog/database.db:/app/database.db:rw 
    environment:
      - NODE_ENV=production
    deploy:
     
      update_config:
       
        delay: 10s
      endpoint_mode: dnsrr
    ports:
      - "3001:3001"

  order-server:
    image: order-service
    build:
      context: .  
      dockerfile: Dockerfile
      target: order  
    volumes:
      - ./order:/app/order:ro  
      - ./nginx:/app/nginx:ro  
    environment:
      - NODE_ENV=production
    deploy:
    
      update_config:
        delay: 10s
      endpoint_mode: dnsrr
    depends_on:
      - catalog-server
    ports:
      - "3002:3002"

  client:
    image: client-service
    build:
      context: .  
      dockerfile: Dockerfile
      target: client 
    volumes:
      - ./frontend:/app/frontend:ro  
    deploy:
    
      update_config:
        
        delay: 10s
      endpoint_mode: dnsrr
    depends_on:
      - catalog-server
      - order-server
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine  
    ports:
      - '8080:80'  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - catalog-server
      - order-server
      - client